apiVersion: velero.io/v1
kind: Restore
metadata:
  name: mysql-persistent-noobaa
  namespace: velero
spec:
  backupName: mysql-persistent-noobaa
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  restorePVs: true
